param(
  [string]$ProtocolVersionFile = 'protocol-version.txt',
  [switch]$Bump
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')
$versionPath = if ([System.IO.Path]::IsPathRooted($ProtocolVersionFile)) {
  $ProtocolVersionFile
} else {
  Join-Path $repositoryRoot $ProtocolVersionFile
}

if (!(Test-Path -LiteralPath $versionPath)) {
  if (!$Bump) {
    throw "Protocol version file '$versionPath' does not exist."
  }

  Set-Content -LiteralPath $versionPath -Value '1' -NoNewline
  $version = 1
  Write-Host 'Protocol version initialized to 1'
} else {
  $raw = (Get-Content -LiteralPath $versionPath -Raw).Trim()
  $version = 0
  if (-not [int]::TryParse($raw, [ref]$version) -or $version -lt 1) {
    throw "Protocol version '$raw' is not a positive integer."
  }

  if ($Bump) {
    $previous = $version
    $version += 1
    Set-Content -LiteralPath $versionPath -Value ([string]$version) -NoNewline
    Write-Host "Protocol version bumped from $previous to $version"
  }
}

$frontendGeneratedDirectory = Join-Path $repositoryRoot 'frontend/src/generated'
$backendGeneratedDirectory = Join-Path $repositoryRoot 'backend/internal/generated/protocolversion'
New-Item -ItemType Directory -Force -Path $frontendGeneratedDirectory | Out-Null
New-Item -ItemType Directory -Force -Path $backendGeneratedDirectory | Out-Null

$frontendGeneratedFile = Join-Path $frontendGeneratedDirectory 'protocolVersion.ts'
$backendGeneratedFile = Join-Path $backendGeneratedDirectory 'protocol_version.go'

Set-Content -LiteralPath $frontendGeneratedFile -Value @"
// Code generated by scripts/generate-protocol-version.ps1; DO NOT EDIT.

export const protocolVersion = $version
"@

Set-Content -LiteralPath $backendGeneratedFile -Value @"
// Code generated by scripts/generate-protocol-version.ps1; DO NOT EDIT.

package protocolversion

const ProtocolVersion = $version
"@

Write-Host "Generated protocol version $version"
